---

- name: deploying kubernestes (step 4 - deploying an ingress controller)
	hosts: master
	vars_files:
		- "group_vars/k8s-ingress.yaml"
		- "group_vars/k8s-master.yaml"
	gather_facts: false
	roles:
		- role: k8s-ingress
